In [28]:
print(type('hola'))
print(type(8))
print(type(True))
print(type(3.25))
print(print)
print(type([1,2,3]))
print(type(list((1,2,3))))
print(type({"nombre":"pepe"}))
print(type((1,2,3)))
print(type(set([1,2,3])))

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>
<built-in function print>
<class 'list'>
<class 'list'>
<class 'dict'>
<class 'tuple'>
<class 'set'>


In [18]:
alumno = {
    "nombre":"pepe",
    "edad":30
}

for key in alumno.keys():
    print(alumno[key])


for v in alumno.values():
    print(v)


pepe
30
pepe
30


In [25]:
for key, value in alumno.items():
    print(key,value)

nombre pepe
edad 30


In [23]:
a = []
a.append(3)
print(a)

[3]


In [24]:
a = ()
a.append(3)
print(a)

AttributeError: 'tuple' object has no attribute 'append'

In [29]:
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [31]:
["Hola"] * 3

['Hola', 'Hola', 'Hola']

In [48]:
import numpy as np

In [49]:
a = [1,2,3,4,5]
b = np.asarray(a)

In [50]:
print(a, type(a))
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [51]:
b * 10

array([10, 20, 30, 40, 50])

In [52]:
b / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [53]:
b

array([1, 2, 3, 4, 5])

In [59]:
b - [5,4,3,2,1]

array([-4, -2,  0,  2,  4])

In [56]:
m = [1,2,3,4,5]
q = [5,4,3,2,1]

for i,e in enumerate(m):
    m[i] = q[i]-m[i]
print(m)

[4, 2, 0, -2, -4]


In [71]:
try:
    print(b - [5,4,3,2,1])
except IndexError as e:
    print("Indice no valido")
except ValueError as e:
    print("invalid shapes")
except Exception as e:
    print("error desconocido")
print("hola")

[-4 -2  0  2  4]
hola


In [73]:
try:
    print(b - [5,4,3,2,"true"])
except IndexError as e:
    print("Indice no valido")
except ValueError as e:
    print("invalid shapes")
print("hola")

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In [75]:
try:
    print(b - [5,4,3,2,"true"])
except IndexError as e:
    print("Indice no valido")
except ValueError as e:
    print("invalid shapes")
except Exception as e:
    raise ValueError("No se pueden sumar estos vectores")
print("hola")

ValueError: No se pueden sumar estos vectores

In [92]:
c = b - [1,2,3,4,5]
c

array([0, 0, 0, 0, 0])

In [84]:
print(5)

5


In [95]:
a =[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [98]:
a = np.asarray([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
list(a)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [100]:
a = np.asarray([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [105]:
print("dimensiones",len(a.shape))
print("shape",a.shape)
print("size", a.size)

dimensiones 2
shape (3, 3)
size 9


In [108]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [109]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [110]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
a[0]

array([1, 2, 3])

In [115]:
a[0,:]

array([1, 2, 3])

In [118]:
a[:,0]

array([1, 4, 7])

In [121]:
z = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
z[:,0]

TypeError: list indices must be integers or slices, not tuple

In [124]:
a = np.eye(5) * 100
a

array([[100.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0., 100.]])

In [125]:
a[0,:]

array([100.,   0.,   0.,   0.,   0.])

In [126]:
a[:,0]

array([100.,   0.,   0.,   0.,   0.])

In [127]:
a[2,2]

100.0

In [129]:

# Fila 0
a[0,:] # o poner: `a[0]`
# Columna 0
a[:,0]
# Indice específico
a[2,2]

100.0

In [140]:
z = np.random.random((5,5))
print(z)

[[0.34260106 0.65593884 0.10204654 0.64907584 0.65292788]
 [0.9152677  0.29634141 0.78530061 0.53264896 0.33329375]
 [0.50312871 0.20616654 0.51683025 0.9498602  0.79814106]
 [0.78513505 0.9188967  0.72069627 0.93499492 0.31554711]
 [0.21881735 0.44289741 0.71858914 0.80220609 0.51858173]]


In [141]:
z[3,3]

0.9349949187184771

In [142]:
z[3,:]

array([0.78513505, 0.9188967 , 0.72069627, 0.93499492, 0.31554711])

In [143]:
z[:,3]

array([0.64907584, 0.53264896, 0.9498602 , 0.93499492, 0.80220609])

In [146]:
z = np.random.random((3,3,3))
print(z.size)
print(z)

27
[[[0.14042707 0.97562149 0.9069311 ]
  [0.73933057 0.82641217 0.43426312]
  [0.56569039 0.7528242  0.11759644]]

 [[0.24176401 0.8354367  0.90207519]
  [0.48787319 0.70037898 0.08172477]
  [0.97355798 0.94836306 0.96349824]]

 [[0.30523527 0.273638   0.82097436]
  [0.83770378 0.18698117 0.58757325]
  [0.31724526 0.4855423  0.84586741]]]


In [154]:
z[2,:,:]

array([[0.30523527, 0.273638  , 0.82097436],
       [0.83770378, 0.18698117, 0.58757325],
       [0.31724526, 0.4855423 , 0.84586741]])

In [155]:
z[:,1,:]

array([[0.73933057, 0.82641217, 0.43426312],
       [0.48787319, 0.70037898, 0.08172477],
       [0.83770378, 0.18698117, 0.58757325]])

In [163]:
z[1,:,1]

array([0.8354367 , 0.70037898, 0.94836306])

In [164]:
z

array([[[0.14042707, 0.97562149, 0.9069311 ],
        [0.73933057, 0.82641217, 0.43426312],
        [0.56569039, 0.7528242 , 0.11759644]],

       [[0.24176401, 0.8354367 , 0.90207519],
        [0.48787319, 0.70037898, 0.08172477],
        [0.97355798, 0.94836306, 0.96349824]],

       [[0.30523527, 0.273638  , 0.82097436],
        [0.83770378, 0.18698117, 0.58757325],
        [0.31724526, 0.4855423 , 0.84586741]]])

In [169]:
z = np.random.random((4,3))
print(z)

[[0.51443656 0.20283463 0.95830808]
 [0.74198612 0.79719049 0.54564675]
 [0.82445536 0.96322097 0.07193159]
 [0.77251026 0.33987004 0.5629436 ]]


In [170]:
z.sum(axis=0)

array([2.85338829, 2.30311612, 2.13883003])

In [171]:
z.sum(axis=1)

array([1.67557927, 2.08482336, 1.85960792, 1.6753239 ])

In [173]:
z.shape

(4, 3)

In [174]:
np.sum(z,axis=0)

array([2.85338829, 2.30311612, 2.13883003])

In [175]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [177]:
print(a,b)

[1 2 3] [4 5 6]


In [178]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [179]:
[1,2,3] + [1,2,3]

[1, 2, 3, 1, 2, 3]

In [181]:
a = np.random.random((2,2))
b = np.random.random((2,2))
print(a)
print(b)

[[0.19425247 0.80198518]
 [0.59134222 0.82264641]]
[[0.98148775 0.11464771]
 [0.52173649 0.6289772 ]]


In [197]:
c = np.concatenate([a,b,b,b,a,b])
c

array([[0.19425247, 0.80198518],
       [0.59134222, 0.82264641],
       [0.98148775, 0.11464771],
       [0.52173649, 0.6289772 ],
       [0.98148775, 0.11464771],
       [0.52173649, 0.6289772 ],
       [0.98148775, 0.11464771],
       [0.52173649, 0.6289772 ],
       [0.19425247, 0.80198518],
       [0.59134222, 0.82264641],
       [0.98148775, 0.11464771],
       [0.52173649, 0.6289772 ]])

In [198]:
c.shape

(12, 2)

In [199]:
c = c.T
print(c)

[[0.19425247 0.59134222 0.98148775 0.52173649 0.98148775 0.52173649
  0.98148775 0.52173649 0.19425247 0.59134222 0.98148775 0.52173649]
 [0.80198518 0.82264641 0.11464771 0.6289772  0.11464771 0.6289772
  0.11464771 0.6289772  0.80198518 0.82264641 0.11464771 0.6289772 ]]


In [196]:
c.shape

(2, 12)

In [191]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [204]:
q = np.concatenate([np.eye(3),np.eye(3)],axis=1)
print(q)

[[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]


In [205]:
q.shape

(3, 6)

In [208]:
q = np.arange(1,10) # python: list(range(10))
print(q)

[1 2 3 4 5 6 7 8 9]


In [212]:
q.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [217]:
z = np.arange(1,21).reshape((10,2))
print(z)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [220]:
np.sum(z, axis=1)

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])

In [223]:
np.max(z, axis=0)

array([19, 20])

In [224]:
np.min(z, axis=0)

array([1, 2])

In [225]:
np.mean(z, axis=0)

array([10., 11.])

In [226]:
np.std(z, axis=0)

array([5.74456265, 5.74456265])

In [234]:
a = np.arange(10)
print(a)
c = a / 0
print(c)

[0 1 2 3 4 5 6 7 8 9]
[nan inf inf inf inf inf inf inf inf inf]


<ipython-input-234-1b2907124d89>:3: RuntimeWarning: divide by zero encountered in true_divide
  c = a / 0
<ipython-input-234-1b2907124d89>:3: RuntimeWarning: invalid value encountered in true_divide
  c = a / 0


In [232]:
np.nan

nan

In [233]:
np.inf

inf

In [238]:
type(c[1])

numpy.float64

In [243]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [244]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [245]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [246]:
np.ones(5)-np.eye(5)

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [248]:
a = np.array(["Hola","que","tal"])

In [254]:
a + ["Hola","Hola","Hola"]

array(['Hola', 'que', 'tal'], dtype='<U4')

In [264]:
q = np.concatenate([a,a]).reshape((2,3))
print(q)
print(q.dtype)

[['Hola' 'que' 'tal']
 ['Hola' 'que' 'tal']]
<U4


In [283]:
q[:,1]

array(['que', 'que'], dtype='<U4')

In [284]:
z = np.ones(5)-np.eye(5)
print(z.dtype)

float64


In [285]:
(np.arange(10) * 10).dtype

dtype('int64')

In [286]:
(np.arange(10)* 10.0).dtype

dtype('float64')

In [287]:
np.array(["asasdf","b","c"]).dtype

dtype('<U6')